#!/usr/bin/env python3

#second version of kab plugin to access insights...
import requests,sys
insights_API_URL="https://access.redhat.com/r/insights/v3"
# note: API docs are at https://access.redhat.com/r/insights/docs/

####################
# Parse command line
####################
if (len(sys.argv) != 3) and (len(sys.argv) != 4):
    print("Usage: ", sys.argv[0], " {RHN_username} {RHN_password} [{account_num}]")
    exit()
RHN_USER=sys.argv[1]
RHN_PASSWORD=sys.argv[2]

##################
# Build websession
##################
websession = requests.Session()
websession.auth = (RHN_USER, RHN_PASSWORD)

if len(sys.argv) == 4:
    request_parms = { 'account_number': sys.argv[3] }
    websession.params = request_parms

#################
# Collect reports
#################
report_data = websession.get(insights_API_URL + "/exports/reports").text.split("\n")
print(*report_data, sep = "\n")